name: Docker Image CI

on:
  push:
    -tags:
      - v1.2.0


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: kucoincommunitychain/kcc
          tags: latest, v1.2.0
          labels: release
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
          
      - name: Copy binary out of image
        run: mkdir -p build/bin && docker create --name binContainer wyblockchain/kcc:latest && docker cp binContainer:/usr/local/bin/geth build/bin/geth && ls -la build/bin/geth
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.KCC_GITHUB_TOKEN }}"
          automatic_release_tag: "v1.2.0"
          prerelease: false
          title: "Ishikari"
          files: |
              build/bin/geth 
      
  
          
          
          
    
